# https://jeong-pro.tistory.com/159
# yaml파일 설정
spring:
  profiles:
    include: oauth,real-db
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    show_sql: true
  session:
    store-type: jdbc
  http:
    encoding:
      charset: UTF-8
      enable: true
      force: true